# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# MD013/line-length - Line length
MD013:
  line_length: 200
  heading_line_length: 100
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements: [br, sub, sup, details, summary]

MD034: true

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: fenced

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true
